config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :dogs, only:[:index, :create, :destroy]
    member do
      get :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :notifications, only: [:index]
  
  get 'search' => "searches#search"
  
  get '/post/hashtag/:hash_name' => 'posts#hashtag',as: 'hashtag_name'
  get '/post/hashtag' => 'posts#hashtag'

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
    @user.create_notification_follow!(current_user)
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end

  #フォロー一覧ページとフォロワー一覧ページ用
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー中", relationship_path(user.id), method: :delete , class: "fas fa-check btn btn-block btn-secondary"%>
  <% else %>
    <%= link_to "フォロー", relationships_path(user_id: user.id), method: :post , class: "fas fa-plus btn btn-block btn-primary"%>

  <% end %>
<% end %>

app/views/relationships/_follow_count.html.erb
<td class="align-middle"><%= user.followings.count %></td>
<td class="align-middle"><%= user.followers.count %></td>

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="d-flex">
      <h3 style='color: #82654D; font-size: 35px;'>Followers</h3>
      <p class='mt-3' style='font-size: 20px;'>ーフォロワーー</p>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-sm-9">
      <% if @users.exists? %>
        <table class="table table-sm">
          <thead>
            <tr>
              <th></th>
              <th>ニックネーム</th>
              <th>フォロー数</th>
              <th>フォロワー数</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', size: "50x50", fallback: "no-image-icon.jpg",class: "rounded-circle" %>
                  <% end %>
                </td>
                <td class="align-middle"><%= link_to user.name, user_path(user) %></td>
                <%= render 'relationships/follow_count', user: user %>
                <td class="align-middle"><%= render 'relationships/follow_btn', user: user %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="d-flex">
      <h3 style='color: #82654D; font-size: 35px;'>Followings</h3>
      <p class='mt-3' style='font-size: 20px;'>ーフォロー中ー</p>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-sm-9">
      <% if @users.exists? %>
        <table class="table table-sm">
          <thead>
            <tr>
              <th></th>
              <th>ニックネーム</th>
               <th>フォロー数</th>
               <th>フォロワー数</th>
               <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', size: "50x50", fallback: "no-image-icon.jpg",class: "rounded-circle" %>
                  <% end%>
                </td>
                <td class="align-middle"><%= link_to user.name, user_path(user) %></td>
                <%= render 'relationships/follow_count', user: user %>
                <td class="align-middle"><%= render 'relationships/follow_btn', user: user %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>