config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :dogs, only:[:index, :create, :destroy]
    member do
      get :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :notifications, only: [:index]
  
  get 'search' => "searches#search"
  
  get '/post/hashtag/:hash_name' => 'posts#hashtag',as: 'hashtag_name'
  get '/post/hashtag' => 'posts#hashtag'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true,
          length: { in: 1..255 }
         validates :introduction,
          length: { maximum: 140 }
         
  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :dogs, dependent: :destroy
  
  def current_user(current_user)
    self.id = current_user.id
  end


# フォロー・フォロワー
  #フォローしているuser達
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  #フォローされているuser達
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  #ユーザーをフォローする
  def follow(user_id)
    relationships.create(follow_id: user_id)
  end

  #ユーザーのフォローを外す
  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    followings.include?(user)
  end


# 通知機能
  # 自分からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def create_notification_follow!(current_user)
    # フォローされているか検索
    notifications = Notification.where(visitor_id: current_user.id, visited_id: id, action: 'follow')
    # フォローされていない場合、同じ通知レコードが存在しないときのみ、通知レコードを作成
    if notifications.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

# 未確認の通知を検索するメソッド
  def unchecked_notifications
    
    passive_notifications.where(checked: false)
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_user, only:[:edit, :update]

  def index
    @user = current_user
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).order(created_at: :desc).per(15)
  end

  #いいね一覧
  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorites_posts = Post.where(id: favorites).page(params[:page]).order(created_at: :desc).per(12)
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "プロフィールを更新しました。"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end

  def ensure_user
    @user = User.find(params[:id])
     unless @user == current_user
     redirect_to user_path(@user)
     end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<!--ユーザー詳細サイドバー-->
<div class="d-flex justify-content-center align-items-center mb-2">
  <%= link_to edit_user_path(user) do %>
    <%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image-icon.jpg", size: "80x80", class: "rounded-circle" %>
  <% end %>
</div>
<div class="text-center align-items-center mb-2">
  <%= user.name %>
</div>
<hr>
<strong>自己紹介</strong><br>
  <% if user.introduction.present? %>
    <%= user.introduction %>
  <% else %>
    <div class="small text-muted">
    （自己紹介文がまだ記入されてません）
    </div>
  <% end %>

<table class="table">
  <tbody>
    <tr>
      <th scope="row">
        投稿数
      </th>
      <td class="align-items-center">
        <%= user.posts.count %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        フォロー中
      </th>
      <td class="align-items-center">
        <%= link_to user_followings_path(user) do %>
          <%= user.followings.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        フォロワー
      </th>
      <td class="align-items-center">
        <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>


<div class= "my-4">
  <% if @user.id == current_user.id %>
    <%= link_to " プロフィール編集", edit_user_path(user), class: "fas fa-user-edit btn btn-block btn-outline-secondary" %>
  <% else %>
    <%= render 'relationships/follow_btn', user: user %>
  <% end %>
  <%= link_to " いいね一覧", favorites_user_path(user), class: "fas fa-heart favorites-post btn btn-block btn-outline-secondary"%>
  <%= link_to " わんちゃん", user_dogs_path(user), class: "fas fa-dog dog-link btn btn-block btn-outline-secondary" %>
  <%= link_to " 投稿一覧", user_path(user), class: "fas fa-user btn btn-block btn-outline-secondary"%>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 edit-user-box mx-auto text-center shadow rounded px-0 my-5">
      <h3 class="user-send py-4"><i class="fas fa-user-edit"></i>マイページ編集</h3>
      
      <% if @user.errors.any? %>
        <ul class="user-alert", style="list-style: none;">
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="px-3 py-3 text-left">
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :profile_image, "プロフィール画像" ,class: "form-control-file",style: "font-weight: bold;" %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no-image-icon.jpg" %>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>

          <div class="form-group">
            <%= f.label :name, "ニックネーム" ,style: "font-weight: bold;"%>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :introduction, "自己紹介 (最大140文字)" ,style: "font-weight: bold;"%>
            <%= f.text_area :introduction, autofocus: true, class: 'form-control' ,size: "50x5" %>
          </div>

          <%= f.submit "\uf4ff変更を保存", style:'font-family: FontAwesome', class: "btn btn-block btn-info mt-5 mb-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container px-2 px-sm-0">
  <div class="row mt-4">
    <div class="col-md-3">
      <%=render "info" ,user: @user %>
    </div>
    <div class="col-md-9">
      <div class="d-flex">
        <h3 style='color: #82654D; font-size: 35px;'>Favorites</h3>
        <p class='mt-3' style='font-size: 20px;'>ーいいね一覧ー</p>
      </div>

      <div class="row mb-4">
        <% if @favorites_posts.present? %>
          <%= render 'posts/index', posts: @favorites_posts %>
        <% end %>
      </div>
      <%= paginate @favorites_posts %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col d-flex">
      <h3 style='color: #82654D; font-size: 35px;'>Users</h3>
      <p class='mt-3' style='font-size: 20px;'>ーユーザー一覧ー</p>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-sm-9">
      <table class="table table-sm">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', size: "50x50", fallback: "no-image-icon.jpg",class: "rounded-circle" %>
                <% end %>
                </td>
              <td class="align-middle"><%= link_to user.name , user_path(user) %></td>
              <%= render 'relationships/follow_count', user: user %>
              <td class="align-middle"><%= render 'relationships/follow_btn', user: user %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="container px-1 px-sm-0">
  <div class="row mt-4">
    <div class="col-md-3">
      <%=render "info" ,user: @user %>
    </div>
    <div class="col-md-9">
      <div class="d-flex">
        <h3 style='color: #82654D; font-size: 35px;'>Post Page</h3>
        <p class='mt-3' style='font-size: 20px;'>ー投稿一覧ー</p>
      </div>
      <div class="row mb-4">
        <%= render "posts/index", posts: @posts %>
      </div>
      <%= paginate @posts %>
    </div>
  </div>
</div>