config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :dogs, only:[:index, :create, :destroy]
    member do
      get :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :notifications, only: [:index]
  
  get 'search' => "searches#search"
  
  get '/post/hashtag/:hash_name' => 'posts#hashtag',as: 'hashtag_name'
  get '/post/hashtag' => 'posts#hashtag'

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments,dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :hashtag_posts, dependent: :destroy
  has_many :hashtags, through: :hashtag_posts


#PostImageのimageを取得
  accepts_attachments_for :post_images, attachment: :image

  enum category:{"公園": 0, "自然": 1, "ドッグラン": 2, "レストラン": 3, "カフェ": 4, "ショップ": 5, "宿泊施設": 6, "複合施設": 7, "牧場": 8, "道の駅": 9,"遊園地": 10,"美術館/博物館": 11,"その他": 12}

  validates :place, presence: true,
    length: { maximum: 255 }
  validates :address, presence: true
  validates :category, presence: true
  validates :body, presence: true,
    length: { maximum: 1000 }


# 通知
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合で、いいねした１度のみ、通知レコードを作成（押した数通知がいくのを防止）
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分で行う自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

#ハッシュタグ
  after_create do
    post = Post.find_by(id: id)
    #hashbodyに打ち込まれたハッシュタグを検出
    hashtags =hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の#を外した上で保存
      if hashtag.include?("#")
        tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
      elsif  hashtag.include?("＃")
        tag = Hashtag.find_or_create_by(hashname: hashtag.delete('＃'))
      end
      post.hashtags << tag
    end
  end

  before_update do
    post = Post.find_by(id: id)
    post.hashtags.clear
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      if hashtag.include?("#")
        tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
      elsif  hashtag.include?("＃")
        tag = Hashtag.find_or_create_by(hashname: hashtag.delete('＃'))
      end
      post.hashtags << tag
    end
  end
  
  #キーワード検索
  def self.search(keyword)
    return [] if keyword.blank?
    
    hashtag_ids = Hashtag.where('hashname LIKE ?', "%#{keyword}%").pluck(:id)
    hashtag_post_ids = HashtagPost.where(hashtag_id: hashtag_ids).pluck(:post_id)
    hashtag_posts = Post.where(id: hashtag_post_ids)
    posts = Post.where(['place LIKE ? OR address LIKE ? OR body LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    result = (posts + hashtag_posts).uniq
    result.sort_by! { |data| data[:created_at] }.reverse!
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index, :show]
  before_action :ensure_user, only:[:edit, :update, :destroy]

  def new
    @post = Post.new
    @post.post_images.build
  end


  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿が完了しました。"
      redirect_to post_path(@post)
    else
      render :new
    end
  end


  def index
    @posts = Post.page(params[:page]).reverse_order.per(15)
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
    #変数をJSで使えるようにするため
    gon.post = @post
    @post_comment = PostComment.new
  end


  def edit
    @post_images = @post.post_images
  end


  def update
    if @post.update(post_params)
      flash[:notice] = "変更が完了しました。"
      redirect_to post_path(@post)
    else
      @post_images = @post.post_images
      render :edit
    end
  end


  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to posts_path
  end

#ハッシュタグ一覧
  def hashtag
    @user = current_user
    if params[:hash_name].nil?
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.posts.count}
    else
      @hashtag = Hashtag.find_by(hashname: params[:hash_name])
      @posts = @hashtag.posts.page(params[:page]).per(15).reverse_order
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.posts.count}
    end
  end


  private

  def post_params
    params.require(:post).permit(:place, :address, :category, :purpose, :latitude, :longitude, :body, :hashbody, post_images_images: [], hashtag_ids: [])
  end


  def ensure_user
    @post = Post.find(params[:id])
     unless @post.user == current_user
     redirect_to posts_path
     end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(hashbody)
    hashbody.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/post/hashtag/#{word.delete("#")}",data: {"turbolinks" => false} }.html_safe
  end
end

app/views/posts/_error_messages.html.erb
<% if post.errors.any? %>
  <ul class="posts-alert", style="list-style: none;">
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/posts/_index.html.erb
<!--投稿一覧-->
<% posts.each do |post| %>
<div class="col-md-6 col-lg-4">
  <div class="post-box p-2">
    <div class="d-flex">
      <%= post.created_at.strftime("%Y/%m/%d")%>
      <div class="favorite-btn-<%= post.id %>">
        <%= render partial: 'favorites/favorite_btn', locals: { post: post }%>
      </div>
      <%= render 'post_comments/comment_count' , post: post %>
    </div>
	  
	  <%= link_to post_path(post) do %>
	    <ul class="slider">
	      <% if post.post_images.present? %>
          <% post.post_images.each do |image| %>
            <li>
              <%= attachment_image_tag image, :image, format: 'jpeg', class: 'post-index-image img-fluid' %>
            </li>
          <% end %>
        <% else %>
          <%= image_tag 'no-image.jpg', style: 'width:100%' %>
        <% end %>
      </ul>
      <%= post.place %>
    <% end %>
    
    <%= simple_format(post.address.truncate(18))%>
    <% if post.hashtags.present? %>
      <%= simple_format(post.hashbody.truncate(15))%>
    <% else %>
      <%= simple_format(post.body.truncate(15))%>
    <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 new-post-box mx-auto text-center shadow rounded px-0 my-5">
      <h3 class="post-send py-4"><i class="far fa-edit fa-fw"></i>編集</h3>
      
      <%= render "error_messages", post: @post %>
      
      <div class="px-3 py-3 text-left">
        <%= form_with model:@post, local:true do |f| %>
          <div class="form-group">
            <%= f.label :image, "画像",class: "form-control-file" ,style: "font-weight: bold;"%>
            <% @post_images.each do |post_image| %>
              <%= attachment_image_tag post_image, :image, :fill, 60, 60 %>
            <% end %>
            <%= f.attachment_field :post_images_images, multiple: true %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :place, "場所名" ,style: "font-weight: bold;"%></div>
            <%= f.text_field :place, class: 'form-control' %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :address, "住所" ,style: "font-weight: bold;"%></div>
            <%= f.text_field :address, class: 'form-control'  %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :category, "カテゴリー" , style: "font-weight: bold;"%></div>
            <%= f.select :category, Post.categories.keys, {prompt: "選択してください"}, class: "form-control" %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :body, "感想" ,style: "font-weight: bold;"%></div>
            <%= f.text_area :body, class: 'form-control' ,size: "50x5" %>
          </div>

          <div class="form-group">
            <%= f.label :hashbody, "ハッシュタグ入力欄" , style: "font-weight: bold;"%>
            <%= f.text_area :hashbody, class: "form-control",size: "50x3" %>
          </div>


          <%= f.submit "\uf044変更を保存", style:'font-family: FontAwesome', class: "btn btn-block btn-success mt-5 mb-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/hashtag.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-md-6 d-flex">
      <h3 style='color: #82654D; font-size: 35px;'>Hashtags</h3>
      <p class='mt-3' style='font-size: 20px;'>ータグ一覧ー</p>
    </div>

    <div class="col-md-6 text-right post-plus">
      <%=link_to " ", new_post_path ,class: "far fa-plus-square", style: "color: #82654D; font-size: 50px;"%>
    </div>
  </div>
  <div class="row my-3">
    <% unless params[:hash_name] == nil %>
      <%= render 'posts/index', posts: @posts %>
    <% end %>
  </div>
  
  <!--上のrow中に以下入れるとページネーションのレイアウトが中央にならないため再度記入-->
  <% unless params[:hash_name] == nil %>
    <%= paginate @posts %>
  <% end %>
  

  <div class="row mb-4">
    <div class= "col-md-12">
      <div class= "hashtag-name">
        <% @hashtags.sort.reverse.each do |count| %>
          <% count[1].each do |hashtag| %>
            <p>
              <%= link_to  "##{hashtag.hashname} (#{hashtag.posts.count}) 件","/post/hashtag/#{hashtag.hashname}",data: {"turbolinks" => false} %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-md-6 d-flex">
      <h3 style='color: #82654D; font-size: 35px;'>New Arrival</h3>
      <p class='mt-3' style='font-size: 20px;'>ー新着ー</p>
    </div>
    <div class="col-md-6 text-right post-plus mb-2">
      <%=link_to " ", new_post_path ,class: "far fa-plus-square", style: "color: #82654D; font-size: 50px;"%>
    </div>
  </div>

  <div class="row mb-4">
    <%= render 'posts/index', posts: @posts %>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 new-post-box mx-auto text-center shadow rounded px-0 my-5">
      <h3 class="post-send py-4"><i class="fas fa-pencil-alt fa-fw"></i>新規投稿</h3>
      
      <%= render "error_messages", post: @post %>
      
      <p class="px-3 py-1 text-left"><font color="#ff0000">*必須</font></p>
      
      <div class="px-3 py-1 text-left">
        <%= form_with model:@post, local:true do |f| %>
          <div class="form-group">
            <%= f.label :image, "画像(複数可)" ,class: "form-control-file" ,style: "font-weight: bold;"%>
            <%= f.attachment_field :post_images_images, multiple: true %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :place, "場所名" ,style: "font-weight: bold;"%></div>
            <%= f.text_field :place, :placeholder => "例：◯◯カフェ", class: "form-control" %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :address, "住所" ,style: "font-weight: bold;"%></div>
              <%= f.text_field :address, :placeholder => "◯◯県△△市□□町1234", class: "form-control" %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :category, "カテゴリー" , style: "font-weight: bold;"%></div>
              <%= f.select :category, Post.categories.keys, {prompt: "選択してください"},style: "font-weight: bold;",class: "form-control" %>
          </div>

          <div class="form-group">
            <div class="required"><%= f.label :body, "感想" , style: "font-weight: bold;"%></div>
              <%= f.text_area :body, :placeholder => "例：屋外、屋内ともに愛犬と一緒に入れるカフェです。〇〇メニューをきれいに食べてくれました。またテラス席のソファから見える景色が美しく、きれいな写真が撮れました！", class: "form-control",size: "50x6" %>
          </div>

          <div class="form-group">
            <%= f.label :hashbody, "ハッシュタグ入力欄" , style: "font-weight: bold;"%>
            <%= f.text_area :hashbody, :placeholder => "例：#高齢犬 #犬用フード #全犬種可 #屋内OK #写真映え #ケージ不要 #テラス席 #おしゃれカフェ", class: "form-control",size: "50x3" %>
          </div>

          <%= f.submit "\uf1d8投稿", style:'font-family: FontAwesome', class: "btn btn-block btn-success mt-5 mb-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container px-2 px-sm-0">
  <div class="row mt-3">
    <!--画像スライダー-->
    <div class="col-md-6 mt-3">
      <h5><%= @post.place %></h5>
      <% if @post.post_images.present? %>
        <div class="slider">
          <% @post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, format: "jpeg", size: "350x250" %>
          <% end %>
        </div>
      <% else %>
        <%= image_tag "no-image.jpg", format: "jpeg", size: "340x250"%>
      <% end %>
      <div class="d-flex">
        <!--いいねボタン-->
        <div class="favorite-btn-<%= @post.id %>">
          <%= render partial: 'favorites/favorite_btn', locals: { post: @post }%>
        </div>
        <!--コメント件数-->
        <div class="comment-count">
          <%= render 'post_comments/comment_count',post: @post %>
        </div>
      </div>
    </div>

    <div class="col-md-6 mt-3">
      <div class="form-inline">
        <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 35, 35, format: 'jpeg', size: "35x35", fallback: "no-image-icon.jpg" ,class: "rounded-circle" %>
        <% end %>
        <div class="align-middle"><%= link_to @user.name, user_path(@user) %></div>
      </div>
      <p class="text-right">投稿日:<%= @post.created_at.strftime("%Y/%m/%d") %></p>
            <%= @post.body %><br>
      <% @post.hashtags.each do |hashtag| %>
        <%= link_to "#" + hashtag.hashname , hashtag_name_path(hashtag.hashname) %>
      <% end %>
      <hr>
      <strong>場所の情報</strong><br>
      『<%= @post.place %>』<br>
      カテゴリー: <%= @post.category %><br>
      <i class="fas fa-map-marker fa-fw"></i><%= @post.address %>
      
      <hr>
      <% if current_user != nil %>
        <div class="d-flex mt-1 justify-content-end">
          <% if @user.id == current_user.id %>
            <%= link_to " 編集", edit_post_path(@post), class: "fas fa-edit btn  btn-outline-info mr-3" %>
            <%= link_to " 削除", post_path(@post), class: "fas fa-trash btn  btn-outline-dark" , method: :delete ,"data-confirm" => "本当に投稿を削除しますか？" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row my-3">
    <div class="col-md-6">
      <h5>Map</h5>
      <div class="d-flex align-items-center">
        <div id='map'></div>
        <style>
        #map{
          width: 340px;
          height: 250px;
        }
        </style>

        <script>
          let map
          let geocoder

          function initMap(){
            // geocoderを初期化
            geocoder = new google.maps.Geocoder();

            map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 15
            });
              // 住所入力を取得
            let inputAddress = `${gon.post.address}`;

            // geocodingしたあとmapを移動
            geocoder.geocode( { 'address': inputAddress}, function(results, status) {
              if (status == 'OK') {
          // map.setCenterで地図が移動
                map.setCenter(results[0].geometry.location);

          // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
                var marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location
                });
              } else {
                alert('Geocode was not successful for the following reason: ' + status);
              }
            });
          }

        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
      </div>
    </div>

    <div class="col-md-6 my-3">
      <h5>コメント</h5>
      <!--コメント一覧-->
      <div class="comment-index">
        <%= render 'post_comments/comment_index', post: @post %>
      </div>
      <!--コメントフォーム-->
      <div class="comment">
        <%= render 'post_comments/comment', post: @post, post_comment: @post_comment %>
      </div>
    </div>
  </div>
</div>