config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :dogs, only:[:index, :create, :destroy]
    member do
      get :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :notifications, only: [:index]
  
  get 'search' => "searches#search"
  
  get '/post/hashtag/:hash_name' => 'posts#hashtag',as: 'hashtag_name'
  get '/post/hashtag' => 'posts#hashtag'

end

app/views/layouts/_bell.html.erb
<%= link_to notifications_path do %>
  <% if user_signed_in? && current_user.unchecked_notifications.any? %>
    <i class="fas fa-bell fa-2x faa-ring animated text-dark"></i>
    <i class="fas fa-circle" style="color:Tomato"></i>
  <% else %>
    <i class="fas fa-bell fa-2x text-dark"></i>
  <% end %>
<% end %>

app/views/layouts/_flash_window.html.erb
<div class="flash-window hidden">
  <p><%= notice %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-footer text-white py-2 fixed-bottom">
  <div class="row">
    <div class="mx-auto">
      <ul class="p-0 m-0 list-unstyled list-inline">
        <li class="list-inline-item">
          <a href="" title="About" class="text-white-50"><small>© 2021 Dog and Me</small></a>
        </li>
        <li class="list-inline-item">
          <a href="" title="License informations" class="text-white-50"><small>プライバシーポリシー</small></a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-header fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag 'logo.jpeg',size: '80x80' , class: 'logo'%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto ">
        <li>
          <%= form_with(url: search_path, local: true, method: :get, class: "nav-link search-form") do |f| %>
            <%= f.search_field :keyword, placeholder: "キーワードで検索",size: "20", class:"border-0 col-10'"%>
            <%= f.submit  "\uf002", style:'font-family: FontAwesome',class: "btn btn-default text-dark px-0 py-1" %>
          <% end %>
        </li>
        <li>
          <%= link_to posts_path ,class: 'nav-link text-dark' do%>
            <i class="fas fa-dog fa-fw faa-shake animated-hover"></i><strong>一覧</strong>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li>
            <%= link_to post_hashtag_path ,class: 'nav-link text-dark' do%>
              <i class="fas fa-hashtag fa-fw faa-shake animated-hover"></i><strong>タグ一覧</strong>
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path ,class: 'nav-link text-dark' do%>
              <i class="far fa-plus-square fa-fw faa-bounce animated-hover"></i><strong>投稿する</strong>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user.id) ,class: 'nav-link text-dark' do%>
              <i class="fas fa-user fa-fw faa-vertical animated-hover"></i><strong>マイページ</strong>
            <% end %>
          </li>
          <li>
            <%= link_to users_path ,class: 'nav-link text-dark' do%>
              <i class="fas fa-users fa-fw faa-vertical animated-hover"></i><strong>ユーザー</strong>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete ,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt fa-fw faa-flash animated-hover"></i><strong>ログアウト</strong>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path ,class: 'nav-link text-dark' do%>
              <i class="fas fa-paw fa-fw faa-shake animated-hover"></i><strong>Dog and Meとは</strong>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path ,class: 'nav-link text-dark' do%>
              <i class="fas fa-user-plus fa-fw faa-vertical animated-hover"></i><strong>新規登録</strong>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-dark' do%>
              <i class="fas fa-sign-in-alt fa-fw faa-vertical animated-hover"></i><strong>ログイン</strong>
            <% end %>
          </li>
        <% end %>
        <li>
          <% if user_signed_in? %>
            <%= render 'layouts/bell' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<%= link_to notifications_path do %>
    <% if user_signed_in? && current_user.unchecked_notifications.any? %>
        <i class="fas fa-bell fa-lg.fa-stack-2x" style="font-size: 1.5em;"></i>
        <i class="fas fa-circle n-circle.fa-stack-1x"></i>
    <% else %>
        <i class="fas fa-bell fa-lg" style="font-size: 1.5em;"></i>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog and Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--gonというGemを使用-->
    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3507c66765.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.css" type="text/css" media="all" />

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">

  </head>

  <body>
    <%= render 'layouts/header' %>

    <main>
      <div class="main">
        <%= yield %>
          <% if flash[:notice] %>
            <%= javascript_include_tag 'flash_window' %>
          <% end %>
        <%= render partial: 'layouts/flash_window' %>
      </div>
    </main>

    <%= render 'layouts/footer' %>
  </body>

</html>